#!/bin/bash

echo "All the variables passed: $@"
echo "Count of variables passed: $#"
echo "All Arguments in single string: $*"
echo "Present working directory: $pwd"
echo "Present working directory of user: $home"
echo "script name: $0"
echo "process id of current script: $$"
sleep 60 &
echo "process id of the last command in background: $!"
echo "Exit status of most recently excuted command: $?"
echo "Current option set for shell: $-"
echo "Last argument of the previous command executed: $_"
echo "Full pathname used to invoke the bash: $BASH"
echo "Bash version: $BASH_VERSION"
echo "path of the current shell: $SHELL"
echo "Random integer: $RANDOM"
echo "current usedid: $UID"
echo "effective userid of current user: $EUID"